language: php

php:
 - 7.0
 - 7.1
 - 7.2
 - 7.3
 - 7.4

before_script:
 - if [ -n "$GITHUB_ACCESS_TOKEN" ]; then composer config github-oauth.github.com ${GITHUB_ACCESS_TOKEN}; fi;
 - composer install --prefer-dist

script:
 - ./tests/run-tests.sh

cache:
 directories:
  - vendor

notifications:
 email: false
